const AUTHENTICATE = "AUTHENTICATE";
const REGISTER = "REGISTER";
const LOG_IN = "LOG_IN";
const LOG_OUT = "LOG_OUT";
const DATA = "DATA";
const ERORR = "ERROR";
const LOADING = "LOADING";
const ADD_TO_CART = " ADD_TO_CART";
const REMOVEFROMCART = "REMOVEFROMCART";

export const Actions = {
  AUTHENTICATE,
  LOG_IN,
  LOG_OUT,
  DATA,
  ERORR,
  LOADING,
  REGISTER,
  ADD_TO_CART,
  REMOVEFROMCART,
};
